export { calendarFeedService, workspaceService } from "@/modules/workspace/api";
export {
  formatCustomerOptionDetail,
  getCustomerDisplayName,
  interpolateDocumentTemplate,
  resolveDocumentVariables,
  useWorkspaceTaskPage
} from "@/modules/workspace/model";
export type {
  AiAgentSummary,
  AiAgentConfig,
  AiCapabilities,
  AiAgentRagConfig,
  AiAgentRagSource,
  DocumentationAssistantMode,
  DocumentationAssistantAction,
  BoardTemplateSummary,
  BoardTemplatePerspective,
  AutomationCapabilities,
  AutomationNodeCapability,
  AutomationRunDetail,
  AutomationRunEventSummary,
  AutomationRunListItem,
  AutomationSideEffectSummary,
  AutomationStepRunSummary,
  DocumentVariableContext,
  DocumentVariables,
  RunDocumentationAssistantInput,
  RunDocumentationAssistantResult,
  CalendarFeedSnapshot,
  CalendarIntegrationProvider,
  CalendarIntegrationStatus,
  CommercialDocumentStatus,
  DocumentLinkedEntityType,
  DocumentKind,
  Customer,
  CustomerAddress,
  CustomerStatus,
  CreateCustomerInput,
  CreateTaskInput,
  UpdateTaskInput,
  ExternalCalendarEvent,
  TaskScheduleInput,
  WorkspaceAutomation,
  WorkspaceBoardMode,
  WorkspaceDocument,
  WorkspaceDocumentFolder,
  WorkspaceDocumentMetadata,
  WorkItemFieldBindingInput,
  WorkItemLinkedDocument,
  WorkspaceDateFormat,
  WorkspacePreferences,
  WorkspaceProfile,
  WorkspacePermissionKey,
  WorkspaceInvite,
  PublicWorkspaceInvite,
  WorkspaceSummary,
  WorkspaceTemplateKey,
  WorkspaceTemplateOption,
  WorkspaceSnapshot,
  WorkspaceAccessControlMember,
  WorkspaceAccessControlSnapshot
} from "@/modules/workspace/model";
export { WorkspaceProvider, useWorkspace } from "@/modules/workspace/providers";
