export { AppRoutes } from "@/app/router/app-routes";
export {
  buildWorkspaceAiAgentsPath,
  buildWorkspaceAutomationsPath,
  buildWorkspaceBillingPath,
  buildWorkspaceBoardPath,
  buildWorkspaceBoardPathWithTask,
  buildWorkspaceDashboardPath,
  buildWorkspaceDocumentationPath,
  buildWorkspaceDocumentationPathWithDoc,
  buildWorkspaceFiscalPath,
  buildWorkspaceLeadFlowPath,
  buildWorkspaceLeadsPath,
  buildWorkspaceMarketingPath,
  buildProposalPublicPath,
  buildWorkspaceSelectorPath,
  buildWorkspaceListPath,
  buildWorkspacePath,
  buildWorkspaceSettingsColumnsPath,
  buildWorkspaceSettingsCustomFieldsPath,
  buildWorkspaceSettingsAuditPath,
  buildWorkspaceSettingsItemTypesPath,
  buildWorkspaceSettingsPerspectivesPath,
  buildWorkspaceSettingsWorkflowStatesPath,
  buildWorkspaceSettingsMembersPath,
  buildWorkspaceSettingsPath,
  buildWorkspaceSettingsWorkflowPath,
  routePaths
} from "@/app/router/route-paths";
export type { AppRoutePath } from "@/app/router/route-paths";
