ALTER TYPE "ConnectPaymentOrderStatus" ADD VALUE IF NOT EXISTS 'OVERDUE';
ALTER TYPE "ConnectPaymentOrderStatus" ADD VALUE IF NOT EXISTS 'SUBSCRIPTION_ACTIVE';
ALTER TYPE "ConnectPaymentOrderStatus" ADD VALUE IF NOT EXISTS 'SUBSCRIPTION_CANCELED';
